const express = require("express");
const controller = require("../controllers/schoolAdmin.controller");
const { authenticate } = require("../middleware/auth.middleware");
const { requireRoles } = require("../middleware/role.middleware");
const { memoryUpload } = require("../middleware/upload.middleware");

const router = express.Router();
router.use(authenticate, requireRoles("school_admin"));

router.get("/profile", controller.profile);
router.get("/active-term", controller.activeTerm);
router.get("/term-weeks", controller.termWeeks);
router.get("/terms/:id/weeks", controller.termWeeks);
router.get("/terms", controller.terms);
router.get("/summary", controller.dashboardSummary);
router.get("/enrolment-by-course", controller.enrolmentByCourse);
router.get("/class-progress", controller.classProgress);
router.get("/learners", controller.listLearners);
router.post("/learners", controller.addLearner);
router.post("/learners/bulk-upload", memoryUpload.single("file"), controller.bulkImportLearners);
router.get("/learners/:id/detail", controller.learnerDetail);
router.patch("/learners/:id", controller.updateLearner);
router.patch("/learners/:id/status", controller.setLearnerActive);
router.post("/learners/:id/promotions", controller.promoteLearner);
router.get("/courses", controller.availableCourses);
router.get("/courses/:courseId/certificate-learners", controller.courseCertificateLearners);
router.post("/course-allocations", controller.bulkAllocateCourse);
router.delete("/course-allocations/:courseId", controller.deallocateCourse);
router.get("/submissions", controller.listSubmissions);
router.patch("/submissions/:id/review", controller.reviewSubmission);
router.get("/typing-results", controller.typingResults);
router.get("/typing/global-tests", controller.globalTypingTests);
router.get("/typing/school-tests", controller.schoolTypingTests);
router.post("/typing/school-tests", controller.createSchoolTypingTest);
router.patch("/typing/school-tests/:id", controller.updateSchoolTypingTest);
router.post("/typing/tests/:id/assign", controller.assignTypingTest);
router.get("/typing/assignments", controller.typingAssignments);
router.get("/typing/performance", controller.typingPerformance);
router.get("/quiz-results", controller.quizResults);
router.get("/global-quizzes", controller.globalQuizzes);
router.get("/school-quizzes", controller.schoolQuizzes);
router.post("/school-quizzes", controller.createSchoolQuiz);
router.post("/school-quizzes/:id/questions", controller.addQuestionToSchoolQuiz);
router.post("/school-quizzes/:id/questions/upload", memoryUpload.single("file"), controller.bulkAddQuestionsToSchoolQuiz);
router.post("/quizzes/:id/assign", controller.assignQuiz);
router.get("/quiz-assignments", controller.quizAssignments);
router.get("/quiz-performance", controller.quizPerformance);
router.get("/leaderboards", controller.leaderboards);
router.get("/preferences", controller.preferences);
router.patch("/preferences", controller.updatePreferences);
router.get("/streams", controller.streams);
router.post("/streams", controller.addStream);
router.delete("/streams/:id", controller.deleteStream);

module.exports = router;
